# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01b3bbad7ab39354ea70527d5a84145d423b4bde30ec12cebf9b46681d07cfc4e4d0702023bd2e80eec36571479826dcca8ce8266e168af43aaee7125aad600d

test:
  secret_key_base: 43a976a50cb307f27f7e8da2f536d0cebf8e2705f991cfba865177f898fc5a07a2e092563ca7ba4894af01617f0b4d713a09eb195a1461aa6ae4134e13188ef5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
